Add support for default issues
avilaton/add-msg-issue-prefix-hook pull request #11
Opened 2023-08-24 17:45 UTC by RobertLD

This PR adds an additional parameter that lets a use specify a default issue prefix if one is not found by the provided regex matching.

There are some other minor syntax changes using the walrus operator for ease of readability

2023-08-24 19:09 UTC, avilaton commented
just merged an earlier contribution, please have another look at this one

2023-08-24 19:20 UTC, RobertLD commented
> just merged an earlier contribution, please have another look at this one

I've addressed the merge conflicts

2023-08-25 12:09 UTC, ivysochyn requested changes

2023-08-25 12:09 UTC, ivysochyn commented on add_msg_issue_prefix_hook/add_msg_issue_prefix.py
> +    pattern = re.compile(args.insert_after)
This overrides `pattern` argument which defines regex for finding issue number.

2023-08-25 12:09 UTC, ivysochyn commented on add_msg_issue_prefix_hook/add_msg_issue_prefix.py
> +   if result := get_ticket_id_from_branch_name(pattern, branch):
Indentation.

2023-08-25 12:28 UTC, RobertLD commented on add_msg_issue_prefix_hook/add_msg_issue_prefix.py
> +    pattern = re.compile(args.insert_after)
Doh Embarrassingly bad merge resolution, resolved

2023-08-25 12:35 UTC, ivysochyn approved these changes

2023-08-25 22:01 UTC, merged